# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  pull_request:
    branches:
      - 'main'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run Digestabot
        uses: ./
        with:
          create-pr: false

      - name: Check changes
        run: |
          if [[ $(git diff --stat) == '' ]]; then
            echo 'should exist changes'
            exit 1
          else
            exit 0
          fi
        shell: bash
